  version: '3.7'

  services:
      mongo1:
          image: mongo:4
          container_name: mongo1
          restart: always
          environment: 
              MONGO_INITDB_ROOT_USERNAME: admin
              MONGO_INITDB_ROOT_PASSWORD: test
      mongo2:
          image: mongo:4
          container_name: mongo2
          restart: always
          environment: 
              MONGO_INITDB_ROOT_USERNAME: admin
              MONGO_INITDB_ROOT_PASSWORD: test

      mongo-express:
          image: mongo-express
          container_name: mongo-express
          restart: always
          ports:
              - 8081:8081
          environment: 
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: test
            ME_CONFIG_MONGODB_SERVER: mongo1
